"""Add syntax_rules column to user_preferences

Revision ID: 0d7d75428d76
Revises: e2b61f4dc40b
Create Date: 2024-11-28 09:12:54.725423

"""
from alembic import op
import sqlalchemy as sa
import json

# revision identifiers, used by Alembic.
revision = '0d7d75428d76'
down_revision = 'e2b61f4dc40b'
branch_labels = None
depends_on = None

default_rules = {
    'word_order': True,
    'subject_verb_agreement': True,
    'verb_tense': True,
    'gender_number': True,
    'relative_pronouns': True
}

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'syntax_rules',
            sa.JSON(),
            server_default=json.dumps(default_rules),
            nullable=False
        ))

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_column('syntax_rules')

    # ### end Alembic commands ###
