"""Add correction_prompt

Revision ID: e2b61f4dc40b
Revises: 
Create Date: 2024-11-26 20:00:21.960536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b61f4dc40b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    default_correction_prompt = """Tu es un correcteur de texte professionnel. Corrige le texte suivant en respectant les options sélectionnées:
- Correction grammaticale
- Correction orthographique
- Amélioration du style
- Correction de la ponctuation

Retourne UNIQUEMENT le texte corrigé, sans aucun autre commentaire."""

    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correction_prompt', sa.Text(), server_default=sa.text(f"'{default_correction_prompt}'"), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_column('correction_prompt')

    # ### end Alembic commands ###
